name: C/C++ CI

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: mkdir build-tests
    - name: cd
      run: cd build-tests
    - name: cmake
      run: cmake .. -DCMAKE_BUILD_TYPE=Tests
    - name: make
      run: make
    - name: run-tests
      run: ./tosx
